---
- name: Setup Vprofile Bastion Host
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC setup Variable
      include_vars: vars/bastion_setup

    - name: Import VPC setup Variable
      include_vars: vars/output_vars

    # CREATE KEY PAIR
    - name: Create vprofile ec2 key
      amazon.aws.ec2_key:
        name: vprofile-key
        region: "{{region}}"
      register: key_out

    - name: Save private key into file bastion-key.pem
      ansible.builtin.copy:
        content: "{{key_out.key.private_key}}"
        dest: "./bastion-key.pem"
        mode: 0600
      when: key_out.changed # only if the file is created

    # CREATE SECURITY GROUP
    - name: Create Sec Grp for bastion host
      amazon.aws.ec2_group:
        name: Bastion-host-sg
        description: Allow port 22 from everywhere and all port within sg
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{MYIP}}"
      register: BastionSG_out

    # CREATE BASTION INSTANCE
    - name: Creating Bastion Host
      amazon.aws.ec2:
        key_name: vprofile-key
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{ bastion_ami }}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "Bastion_host"
          Project: Vprofile
          Owner: DevOps Team
        exact_count: 1 # create max 1 instance of this
        count_tag: # if you have this tag one time, then it will not launch the instance again
          Name: "Bastion_host"
          Project: Vprofile
          Owner: DevOps Team
        group_id: "{{BastionSG_out.group_id}}"
        vpc_subnet_id: "{{pubsub1id}}"
      register: bastionHost_out
